### ISSUE TITLE
error when generating qr code from lazy text.

### ISSUE THREAD

**Issue by JamesMackerel** [dprog-philippe-docourt/django-qr-code#1]
```
{% qr_code reverse_lazy_url %}
```
I think 
```python
    encoded_text = str(base64.urlsafe_b64encode(bytes(text, encoding='utf-8')), encoding='utf-8')
```
should be
```python
    encoded_text = str(base64.urlsafe_b64encode(bytes(str(text), encoding='utf-8')), encoding='utf-8')
```

**Comment by philippe-docourt** [comment]
Thanks for your report and your patience.

My understanding is that the problem comes from {% qr_code_url reverse_lazy_url %}, and not {% qr_code reverse_lazy_url %}. I was able to reproduce the problem  qr_code_url only.

**Comment by philippe-docourt** [comment]
Problem is fixed + a test was added for this issue.
