### ISSUE TITLE
Generate qrcode as image file for sending over whatsapp

### ISSUE THREAD

**Issue by sandeepbalagopal09** [dprog-philippe-docourt/django-qr-code#10]
I want to generate an image file of the qrcode for sending in whatsapp. Is it possible to do it using this package ?

**Comment by philippe-docourt** [comment]
Yes, you can! However, there is no shortcut for it (no special Django tag).

After some googling it appears that creating a QR code with this kind of URL is all you need:
`https://api.whatsapp.com/send?phone=<phone-number>&text=<some-text>`
