### ISSUE TITLE
installed and added to installed_apps but problem on django runserver

### ISSUE THREAD

**Issue by kronoszx** [dprog-philippe-docourt/django-qr-code#11]
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'qr_code.templatetags.qr_code': cannot import name 'ERROR_CORRECT_L'

solved adding to my settings:

from qr_code.qrcode import constants

**Comment by hektor7** [comment]
I've came across with this issue too, it's due to qrcode have changed location of these constants. I've solved this situation using downgrading qrcode version to 6.0.

**Comment by philippe-docourt** [comment]
Hi @kronoszx, could you tell me what version of qrcode you are using and how do you reproduce this issue?

**Comment by philippe-docourt** [comment]
Since we migrated to Segno library, the dependency to `ERROR_CORRECT_L` has been completely removed for version 2.0.
