### ISSUE TITLE
Do not use underscores in urls

### ISSUE THREAD

**Issue by dyve** [dprog-philippe-docourt/django-qr-code#16]
In `https://github.com/dprog-philippe-docourt/django-qr-code/blob/master/qr_code/urls.py`, there is a hardcoded section that creates urls with underscores.

```
urlpatterns = [
    path('images/serve_qr_code_image/', views.serve_qr_code_image, name='serve_qr_code_image')
]
```

Using underscores in urls is allowed, but can be considered bad practice, see https://www.quora.com/Is-an-underscore-allowed-in-a-URL. Would you consider using hyphens here instead of underscores? Or just user `serve` instead of `serve_qr_code_image`.

Thanks for this library!

**Comment by philippe-docourt** [comment]
When I started to develop in Python + Django, I thought it was best to use the exact same syntax for the python code (the view), the name of view and the url that serves that view.
However, over the time I started to change all underscores by hyphens in URLs, in all my projects. This one was probably the last one using underscores. The urls.py has been updated to use an hyphen!
