### ISSUE TITLE
Creating dynamic QR codes in template

### ISSUE THREAD

**Issue by simonhjoerg** [dprog-philippe-docourt/django-qr-code#17]
Hi,

Im not sure if its possible, but it would be great if you could pass in variables from the jinja2 template into the qr code.
{% qr_from_text "Hello {{ myVariable }}" size="T" %}

To allow for generation of dynamic QR codes on the fly

**Comment by ashutoshkrris** [comment]
it can be done in the following way:

`{% qr_from_text  myVariable size="T" %}`

I did the same for my URL Shortener project : www.srty.me

**Comment by simonhjoerg** [comment]
huh, not sure how i missed that, it works thanks!
