### ISSUE TITLE
Error when generating png style image.

### ISSUE THREAD

**Issue by ephantuskaranja** [dprog-philippe-docourt/django-qr-code#2]
### Error
I get the following error when generating a  png image from text.
```
save() got an unexpected keyword argument 'format'
```
I narrowed down the error to line 91 of maker.py in qr_code/qrcode/
```img.save(stream, format=PNG_FORMAT_NAME.upper())```

The img object has the method save but it does not take in the parameter format.

### Possible solution
Changing the parameter format to `kind` as shown three lines before in line 88. Fixes the problem.
```img.save(stream, kind=PNG_FORMAT_NAME.upper())```

**Comment by philippe-docourt** [comment]
Hi,
Do you have some code to reproduce this error?

Which version of Pillow do you use? I tried with both version 4.2 and 5.2 and it seems to work fine from what I can see.

NB: The test suite generates sevral PNG images, and it pass without any failure.

**Comment by philippe-docourt** [comment]
No information / cannot reproduce.
