### ISSUE TITLE
Must be something silly, but...

### ISSUE THREAD

**Issue by pmulgaonkar** [dprog-philippe-docourt/django-qr-code#23]
Following the instructions I get the local server started to check out the demo site, but what I get is the django debug screen with:

> 

Using the URLconf defined in demo_site.urls, Django tried these URL patterns, in this order:

    qr-code-demo/
    qr-code/

The current path, qr_code_demo/, didn't match any of these.

**Comment by pmulgaonkar** [comment]
My error. Somehow I had underscores in the address i was trying.

**Comment by philippe-docourt** [comment]
There was indeed an issue after commit [#e5fee343f28d4fa0f5a6b4bd04946fd8020afbe4](https://github.com/dprog-philippe-docourt/django-qr-code/commit/e5fee343f28d4fa0f5a6b4bd04946fd8020afbe4#diff-12762701407d1d1ad4461ec7f3eae34e56cba2e0cd53ad550ea1760679748d8f)
