### ISSUE TITLE
Evaluate escape sequences

### ISSUE THREAD

**Issue by sakyoud-zakaria** [dprog-philippe-docourt/django-qr-code#24]
it seams like qr_from_text  dosn't evaluate escape sequences \t for TAB, \n for ENTER

i tried this with no success

```
{% qr_from_text "value_of_input_1%0Avalue_of_input_2" size="m" %}
{% qr_from_text "value_of_input_1 /t Avalue_of_input_2" size="m" %}
```

I'm i missing something ?

thank you in advance

**Comment by philippe-docourt** [comment]
Interpreting escape sequence would break existing applications using literal '\'.

Having this kind of behavior requires to introduce a way of escaping escape character, and that's sounds needlessly complicated. We would have to define whether we support percent encoding, backslashes, or maybe both?

In your situation, I woulds suggest to use Python variable with the appropriate text. Python handles this feature out of the box.

In your view:
`my_text = "Hello\n\tWorld"`

In your template:
`{% qr_from_text my_text %}`

You can use the 'r' in front of your string to tell that you want the raw text without any escape sequence when escaping is not desired.
