### ISSUE TITLE
Base64 In Emails

### ISSUE THREAD

**Issue by hampton1122** [dprog-philippe-docourt/django-qr-code#25]
We are using your plugin in our Django project to email QR Codes as part of a registration process. Unfortunately, some email clients (Android in particular) do not show base64 images.  Do you have any plans on providing a way for your plugin to render the images differently for this use case? CID perhaps?

**Comment by philippe-docourt** [comment]
CID seems rather outdated and mostly Microsoft oriented.

I'm not sure what more django-qr-code could do for you here. I cannot see how the template tags provided by django-qr-code can help you. You need some logic in your view to attach the image to your e-mail. Do you have a proposal?

As of today you can generate the `<img src="cid:xxxxxx.png" alt="xxxxxx" style="">` tag in your template (e-mail body), and then use the `qr_code.views.serve_qr_code_image` in your view to generate the file (PNG or SVG) to attach to your e-mail.
