### ISSUE TITLE
Problem with admin page when using django-qr-code

### ISSUE THREAD

**Issue by kessero** [dprog-philippe-docourt/django-qr-code#26]
My example app urls.py
`urlpatterns = [
   path('', lost.home, name='home_lost'),
   path('pdf_page', lost.home, include('qr_code.urls', namespace="qr_code"), name='pdf_page')
   ]
`
When i open localhost:8000/admin i get
`

Request Method: | GET
-- | --
http://localhost:8000/admin/
3.1.7
TypeError
'tuple' object is not a mapping
/usr/lib/python3.9/site-packages/django/urls/resolvers.py, line 486, in _populate
/usr/bin/python3
3.9.1

`
If i comment path('pdf_page', lost.home, include('qr_code.urls', namespace="qr_code"), name='pdf_page') admin page works fine?

**Comment by kessero** [comment]
After edit line from:
path('pdf_page', lost.home, include('qr_code.urls', namespace="qr_code"), name='pdf_page')
to:
path('pdf_page', include('qr_code.urls', namespace="qr_code"))
For some reason everything was working only admin site not. After change path seems everything works fine.

**Comment by philippe-docourt** [comment]
Please check out the documentation of `include()` here: https://docs.djangoproject.com/en/3.1/ref/urls/#include
and example here: https://docs.djangoproject.com/en/3.1/topics/http/urls/#including-other-urlconfs
