### ISSUE TITLE
Implement a new app

### ISSUE THREAD

**Issue by oelegeirnaert** [dprog-philippe-docourt/django-qr-code#27]
Hello @philippe-docourt ,

Great work, thank your very much!

Any idea when a payment request qr will be implemented?
Or is it already implemented? If so, please can you tell me how to generate one?

https://en.wikipedia.org/wiki/EPC_QR_code

Many Thanks!

**Comment by philippe-docourt** [comment]
The only thing needed is to build the text (with new lines) that needs to be rendered in the QR code. Then, using a tag like `qr_from_text` will do the job ;-)

Adding a helper to build the required text seems a litlle bit out of the scope of the library, but I'll think about it.

**Comment by heuer** [comment]
Just as a note; Segno already offers support for EPC-QR codes, see <https://segno.readthedocs.io/en/latest/epc-qrcodes.html>. Only a tag would have to be invented for it. Anyway, I don't know if this is beyond the scope of this project. I just thought, I should mention it. ;)

**Comment by philippe-docourt** [comment]
Hi @heuer,

After some digging, I realized that the way template tags from django-qr-code work, imposes some limitations (notably encoding) to what can be reused from Segno, but I decided to implement it :-)

**Comment by philippe-docourt** [comment]
Hi @oelegeirnaert, This feature should be released for version 3. It's available on the master branch. Could you check the documentation of `qr_for_epc` and `qr_url_for_epc` (especially the examples [here](https://github.com/dprog-philippe-docourt/django-qr-code#qr-codes-for-apps), test it, and give me your feedback?
