### ISSUE TITLE
Add support for Jinja2 templates

### ISSUE THREAD

**Issue by destos** [dprog-philippe-docourt/django-qr-code#3]
Was curious if you would be interested in having Jinja2 support added to this module?

I wouldn't mind making an attempt at adding an internal contrib module to add `django-jinja` style template tags and functions.

It could also possibly work as an external module if you aren't interested in adding support within this one.

**Comment by philippe-docourt** [comment]
Hi destos,

Any contribution would be appreciated, including an addition for supporting Jinja templates.

Please provide the appropriate tests for your additional module. You may simply complete some of the existing tests in order to reduce the required work.

I look forward to hearing from you!
