### ISSUE TITLE
setting the border parameter is not passed to segno

### ISSUE THREAD

**Issue by nschlemm** [dprog-philippe-docourt/django-qr-code#31]
The border parameter e.g. mentioned in https://github.com/dprog-philippe-docourt/django-qr-code/blob/e5d944c184759c2453da646d45bb99b512d18b95/README.md#qr-code-rendering-options is not passed to segno https://segno.readthedocs.io/en/latest/api.html#segno.QRCode.save as it is not included in https://github.com/dprog-philippe-docourt/django-qr-code/blob/e5d944c184759c2453da646d45bb99b512d18b95/qr_code/qrcode/utils.py#L139-L153

**Comment by philippe-docourt** [comment]
Good catch!
