### ISSUE TITLE
force_text is removed in Django 4.0

### ISSUE THREAD

**Issue by gldecurtins** [dprog-philippe-docourt/django-qr-code#36]
django-qr-code doesn't support Django 4.0

https://docs.djangoproject.com/en/4.0/releases/4.0/

django.utils.encoding.force_text() and smart_text() are removed.

I wanted to raise a pull request, just replacing force_text with force_str. But then I noticed in .travis.yml you're setting the DJANGO_VERSION to 2.2 and I'm not sure if this would work.

**Comment by philippe-docourt** [comment]
I'll drop support for Django 2.2 and add support for Django 4.0 in Django QR Code 3.1.

**Comment by philippe-docourt** [comment]
Support for Django 4 is available.
