### ISSUE TITLE
QR Codes in email (gmail)?

### ISSUE THREAD

**Issue by ricosalomar** [dprog-philippe-docourt/django-qr-code#39]
When I try to include a qr_code in an email using `qr_url_from_text`, gmail mangles it and it's converted to something like `https://ci3.googleusercontent.com/proxy/...` which is broken.
Any suggestions on how to fix this?

**Comment by philippe-docourt** [comment]
I'm not sure I understand the problem. Could you be more specific?

**Comment by ricosalomar** [comment]
I'll try.
For Gmail accounts, Google serves images from some kind of proxy server. So if I include an image
`<img src="https://foobar.com/media/foo.png" />` the html that a Gmail recipient receives is something like:
`<img src="https://ci4.googleusercontent.com/proxy/KZyptrMEiKtFFW3DxJ4_kzPrBkq2Edojipqz3Z186cw9rhf7XIF195lPF3VXRpQWnJ--nx9aSF9d8rtigwrHEJBBROfIn2rEGJTHh-1RtB_IoA=s0-d-e1-ft#https://foobar.com/media/foo.png" />`
This should work fine, if the src has an image file extension, (.jpg, .png, etc).
But the images generated by django-qr-code don't have an image extension, instead they are like `https://foobar.com/qr_code/images/serve-qr-code-image/?text=NTEyNjg%3D&cache_enabled=1&image_format=png&error_correction=l&boost_error=1&encoding=utf-8`.
Gmail doesn't parse these uris correctly, and it results in broken images. I believe this is a security feature.

**Comment by ricosalomar** [comment]
But wouldn't that give all the images the same URL?

**Comment by philippe-docourt** [comment]
The path of the URL would be the same, but the query argument (after /?) would be different (i.e. the payload and the rendering options are always passed as query arguments.

**Comment by ricosalomar** [comment]
Ah, brilliant.
Thanks, Philippe!
