### ISSUE TITLE
How to retrieve the cached static URL of QR codes

### ISSUE THREAD

**Issue by JoeWHoward** [dprog-philippe-docourt/django-qr-code#4]
How should I go about accessing the actual image URL of the QR code that is generated?  I am passing the retrieved image into Zebra BrowserPrint to be sent to a thermal printer, but it doesn't seem to play nicely with the tokenized image URL.  Any ideas?

Or some direction on where I should look to create my own method that can return a URL.

**Comment by philippe-docourt** [comment]
If you want to serve the image files directly from a view that receives the text to encode (your API view), you can call qr_url_from_text for instance in your own code, and then let the django-qr-code app serve the image URL (you would need to include qr_code.urls into your project URLs).

**Comment by philippe-docourt** [comment]
I added support for customizing usage of URL signature token via template tags (allows to generate URLs for serving QR code images that do not include a signature token).
