### ISSUE TITLE
Generating an image

### ISSUE THREAD

**Issue by jkblgithub** [dprog-philippe-docourt/django-qr-code#40]
Apologies but I cannot understand from your documentation how to simply generate a qrcode as a png/jpg etc. without having to render a template. Is it possible?

**Comment by philippe-docourt** [comment]
What exactly do you want to achieve? If you do not want to use Django tags for rendering QR code in a template, you can simply use the API in your code. For instance, `qr_code.qrcode.maker.make_qr_code_image` will return bytes representing either a PNG or JPEG image depending on the `image_format` passed in the `qr_code_options` parameter.
