### ISSUE TITLE
utils class WifiConfig ignores kwargs (since using @pydantic_dataclass)

### ISSUE THREAD

**Issue by vlt** [dprog-philippe-docourt/django-qr-code#43]
The `@pydantic_dataclass` deorator introduced in 12f68b90bb5f19fa305ed7f7c2ef12b4c22414e8 lets `__init__()` ignore the values from kwargs:

```
WifiConfig(
    ssid="Foo",
)
```

doesn’t work, while

```
WifiConfig(
    "Foo",
)
```

does.

**Comment by philippe-docourt** [comment]
Fixed in version 3.1.2
