### ISSUE TITLE
How to suppress info message "Pillow is not installed. No support available for PNG format."?

### ISSUE THREAD

**Issue by tomas-zemres** [dprog-philippe-docourt/django-qr-code#6]
How to suppress info messages
 "Pillow is not installed. No support available for PNG format."
 in log files?

(because I use only SVG output and I don't have installed Pillow)

I don't want disable whole logger named "django".

**Comment by philippe-docourt** [comment]
You can now customize what to show in the console, thanks to the dedicated logger. Moreover the message uses the debug level.
