### ISSUE TITLE
Django 3.0 compatibility

### ISSUE THREAD

**Issue by timonegk** [dprog-philippe-docourt/django-qr-code#7]
This package uses the `available_attrs` function (https://github.com/dprog-philippe-docourt/django-qr-code/blob/master/qr_code/views.py#L27) which has been removed in Django 3.0 (https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis).

**Comment by subinabid** [comment]
Django 3 has dropped support for  Python 2 as it has reached EOL. Some private APIs which were available in Django 2 were removed in Django 3. **_available_attrs_** is one of them.

`django-qr-code/urls.py` is importing `views.py`
`django-qr-code/urls.py` is importing `available_attrs` which is used in `cache_qr_code()`

Trying to comment out the `import` statement and `cache_qr_code` definition in `views.py`

**Comment by subinabid** [comment]
Tried the above method, got stuck in from `django.utils.six import wraps`. HAd to comment out that too.

**_Quick fix:_**
comment out line 9- 10, 22 - 41, 45

**Comment by subinabid** [comment]
Alternate method for line 10
replace `from django.utils.six import wraps` with `from six import wraps`

**Comment by albertdotpy** [comment]
I got the same error

**Comment by albertdotpy** [comment]
All I had to do is downgrade the 3.0.2 to 2.2.9 :3

**Comment by ronivil** [comment]
> All I had to do is downgrade the 3.0.2 to 2.2.9 :3

Yes, but you cant stay on older versions all the time.

**Comment by tablefiller** [comment]
Having the same problem. This is causing issues on AWS Codestar. Great package.

**Comment by SchrodingersGat** [comment]
This package supports > 3.0 https://github.com/chrissam/django-qr-code

**Comment by philippe-docourt** [comment]
Fixed on release 1.2.0.
