### ISSUE TITLE
type object argument after ** must be a mapping, not str

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [dprog-philippe-docourt/django-qr-code#9]
*   this {% qr_for_contact contact_detail size='S' %} throws a **type error**

**Comment by subinabid** [comment]
try

% qr_for_contact **contact_detail = whatever_you _are_passing_in_context**  size='S' %}

**Comment by philippe-docourt** [comment]
What is the content of contact_detail provided in your example above? It should be an instance of ContactDetail.
